{% set version = "1.4" %}
{% set sha256 = "383de0f537ef2e38b85ff9692593b0cfae8958c9b3bd451b52c255fd9171ffce" %}

package:
  name: autograd
  version: {{ version }}

source:
  fn: autograd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/autograd/autograd-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy >=1.10
    - future >=0.15.2
    - scipy >=0.17

  run:
    - python
    - numpy >=1.10
    - future >=0.15.2
    - scipy >=0.17

test:
  imports:
    - autograd
    - autograd.numpy
    - autograd.scipy
    - autograd.scipy.stats

about:
  home: https://github.com/HIPS/autograd
  license: MIT
  summary: Efficiently computes derivatives of numpy code.

extra:
  recipe-maintainers:
    - richardotis
    - ericmjl
